-- Baseline schema reproduced from production (public schema) for development projects.
-- Structure only: no data, no auth users. Do NOT apply to the production project.
-- Note: shared_set_songs view is omitted (definition not captured; not used by the app).

create extension if not exists pgcrypto with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- Tables
create table public.profiles (
  id uuid not null,
  display_name text,
  role text default 'viewer',
  created_at timestamptz default now(),
  lead boolean not null default false,
  vocal boolean not null default false,
  acoustic boolean not null default false,
  electric boolean not null default false,
  piano boolean not null default false,
  bass boolean not null default false,
  drum boolean not null default false,
  sound boolean not null default false,
  visual boolean not null default false,
  live boolean not null default false,
  phone text,
  full_name text,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade,
  constraint profiles_role_check check (role = any (array['admin','editor','viewer']))
);

create table public.songs (
  id uuid not null default gen_random_uuid(),
  title text not null,
  artist text,
  authors text[],
  language text default 'mn',
  tags text[] default '{}',
  bpm integer,
  time_sig text,
  base_key text,
  capo integer default 0,
  is_public boolean default true,
  created_by uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  owner uuid,
  lyrics text,
  original_key text,
  tempo integer,
  youtube_url text,
  constraint songs_pkey primary key (id),
  constraint songs_created_by_fkey foreign key (created_by) references auth.users(id),
  constraint songs_owner_fkey foreign key (owner) references auth.users(id) on delete set null
);

create table public.setlists (
  id uuid not null default gen_random_uuid(),
  name text not null,
  notes text,
  date date,
  created_by uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint setlists_pkey primary key (id),
  constraint setlists_created_by_fkey foreign key (created_by) references auth.users(id)
);

create table public.setlist_songs (
  id uuid not null default gen_random_uuid(),
  setlist_id uuid,
  song_id uuid,
  key_override text,
  position integer not null,
  constraint setlist_items_pkey primary key (id),
  constraint setlist_items_setlist_id_order_index_key unique (setlist_id, position),
  constraint setlist_items_setlist_id_fkey foreign key (setlist_id) references public.setlists(id) on delete cascade,
  constraint setlist_items_song_id_fkey foreign key (song_id) references public.songs(id) on delete restrict
);

create table public.sets (
  id uuid not null default gen_random_uuid(),
  owner uuid,
  name text not null,
  notes text,
  share_token text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint sets_pkey primary key (id),
  constraint sets_share_token_key unique (share_token),
  constraint sets_owner_fkey foreign key (owner) references auth.users(id) on delete cascade
);

create table public.set_songs (
  set_id uuid not null,
  song_id uuid not null,
  position integer not null,
  transpose integer not null default 0,
  constraint set_songs_pkey primary key (set_id, song_id),
  constraint set_songs_set_id_fkey foreign key (set_id) references public.sets(id) on delete cascade,
  constraint set_songs_song_id_fkey foreign key (song_id) references public.songs(id) on delete cascade
);

create table public.tags (
  id bigint generated by default as identity,
  name text not null,
  constraint tags_pkey primary key (id),
  constraint tags_name_key unique (name)
);

create table public.song_tags (
  song_id uuid not null,
  tag_id bigint not null,
  constraint song_tags_pkey primary key (song_id, tag_id),
  constraint song_tags_song_id_fkey foreign key (song_id) references public.songs(id) on delete cascade,
  constraint song_tags_tag_id_fkey foreign key (tag_id) references public.tags(id) on delete cascade
);

-- Indexes
create index idx_set_songs_position on public.set_songs using btree (set_id, position);
create index idx_songs_title on public.songs using gin (
  to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(lyrics, ''))
);

-- Functions
create or replace function public.set_owner_on_insert()
returns trigger language plpgsql security definer set search_path to 'public'
as $$
begin
  if new.owner is null then new.owner := auth.uid(); end if;
  return new;
end;
$$;

create or replace function public.set_updated_at()
returns trigger language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.share_set(p_set_id uuid)
returns text language plpgsql security definer set search_path to 'public'
as $$
declare v_token text;
begin
  if not exists (select 1 from public.sets s where s.id = p_set_id and s.owner = auth.uid()) then
    raise exception 'not_owner';
  end if;

  v_token := encode(gen_random_bytes(24), 'hex');
  update public.sets set share_token = v_token, updated_at = now() where id = p_set_id;
  return v_token;
end;
$$;

-- Triggers
create trigger sets_set_owner before insert on public.sets for each row execute function public.set_owner_on_insert();
create trigger sets_set_updated_at before update on public.sets for each row execute function public.set_updated_at();
create trigger songs_set_owner before insert on public.songs for each row execute function public.set_owner_on_insert();
create trigger songs_set_updated_at before update on public.songs for each row execute function public.set_updated_at();

-- Row level security (mirrors production: setlists and setlist_songs have RLS DISABLED there,
-- their policies exist but are inactive)
alter table public.profiles enable row level security;
alter table public.songs enable row level security;
alter table public.sets enable row level security;
alter table public.set_songs enable row level security;
alter table public.tags enable row level security;
alter table public.song_tags enable row level security;

-- profiles
create policy "profiles self" on public.profiles for select using (auth.uid() = id);
create policy "profiles_insert" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_insert_public" on public.profiles for insert with check (auth.role() = any (array['anon','authenticated']));
create policy "profiles_select" on public.profiles for select using (auth.uid() = id);
create policy "profiles_select_all_authenticated" on public.profiles for select using (auth.role() = 'authenticated');
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_update" on public.profiles for update using (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id);

-- songs
create policy "Authenticated can insert songs" on public.songs for insert with check (auth.role() = 'authenticated');
create policy "Owner can delete songs" on public.songs for delete using (owner = auth.uid());
create policy "Owner can update songs" on public.songs for update using (owner = auth.uid()) with check (owner = auth.uid());
create policy "Public can read songs" on public.songs for select using (true);
create policy "songs_owner_rw" on public.songs for all using (owner = auth.uid()) with check (owner = auth.uid());
create policy "songs_shared_ro" on public.songs for select using (
  exists (select 1 from public.set_songs ss join public.sets s on s.id = ss.set_id
          where ss.song_id = s.id and s.share_token is not null)
);
create policy "songs_update_all_authenticated" on public.songs for update to authenticated using (true) with check (true);

-- setlists (inactive: RLS disabled, as in production)
create policy "setlists read" on public.setlists for select using (true);
create policy "setlists update by owner or admin" on public.setlists for update using (
  created_by = auth.uid()
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
);
create policy "setlists write by editor" on public.setlists for insert with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = any (array['admin','editor']))
);

-- setlist_songs (inactive: RLS disabled, as in production)
create policy "setlist_items read" on public.setlist_songs for select using (true);
create policy "setlist_items write by editor" on public.setlist_songs for insert with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = any (array['admin','editor']))
);

-- sets / set_songs / tags / song_tags
create policy "sets_owner_rw" on public.sets for all using (owner = auth.uid()) with check (owner = auth.uid());
create policy "sets_shared_ro" on public.sets for select using (share_token is not null);
create policy "set_songs_owner_rw" on public.set_songs for all
  using (exists (select 1 from public.sets s where s.id = set_songs.set_id and s.owner = auth.uid()))
  with check (exists (select 1 from public.sets s where s.id = set_songs.set_id and s.owner = auth.uid()));
create policy "set_songs_shared_ro" on public.set_songs for select
  using (exists (select 1 from public.sets s where s.id = set_songs.set_id and s.share_token is not null));
create policy "song_tags_rw" on public.song_tags for all
  using (exists (select 1 from public.songs s where s.id = song_tags.song_id and s.owner = auth.uid()))
  with check (exists (select 1 from public.songs s where s.id = song_tags.song_id and s.owner = auth.uid()));
create policy "tags_insert" on public.tags for insert with check (auth.uid() is not null);
create policy "tags_ro" on public.tags for select using (true);
